name: Linters via pre commit

on:
  workflow_call:

jobs:
  linters_via_pre_commit:
    name: Linters via pre commit
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10.6 
    - name: Install system hooks
      run: sudo apt install -qq ros-jazzy-ament-uncrustify
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage manual
