name: Linters via pre commit

on:
  workflow_call:

jobs:
  linters_via_pre_commit:
    name: Linters via pre commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/naturerobots/ros2_jazzy_build:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options:
        --user root
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --hook-stage manual
